## Captcha validation service properties
mosip.captcha.api.id=mosip.captcha.id.validate
mosip.captcha.api.version=1.0

## Captcha provider properties
mosip.captcha.module-provider-mapping.default=GoogleReCaptchaV2

## GoogleReCaptchaV2 configuration

# secrets
mosip.captcha.google-recaptcha-v2.secret.preregistration=preregistrationSecret

mosip.captcha.google-recaptcha-v2.verify-url=https://www.google.com/recaptcha/api/siteverify
